### ISSUE TITLE
สอบถามเรื่อง เรื่อง object

### ISSUE THREAD

**Issue by AmAdevs** [ballweera/geek-contact#10]
<img width="1440" alt="screen shot 2560-11-24 at 9 01 05 am" src="https://user-images.githubusercontent.com/31329764/33192586-32d2ff72-d0f6-11e7-8d93-0c331b93eaa0.png">
<img width="1440" alt="screen shot 2560-11-24 at 9 00 57 am" src="https://user-images.githubusercontent.com/31329764/33192582-274a928c-d0f6-11e7-92d7-91f141b5f83e.png">

 อาจารย์ครับ ผมจะนำ object จาก router มาใช้กับ HTTP method ยังไงครับ  ตามรูปเลยครับ ขอบคุณครับ

**Comment by ballweera** [comment]
ให้เขียน logic ของ api ใน router แทนครับ ส่วน module server แค่ register router เท่านั้น

`router.get('/contactlist', (req, res) => {
})`

`app.user('/', router)`
