### ISSUE TITLE
web

### ISSUE THREAD

**Issue by supareak148430** [ballweera/geek-contact#9]
อาจารย์ครับ JS ใช้ของ Angular.JS ไหม หรือต้องแปลงเป็น JS ที่อาจารย์สอน

**Comment by ballweera** [comment]
AngularJS 2-5 ใช้ TypeScript ครับ และโปรเจ็คนี้ ไม่ได้ให้เขียน Angular แต่ให้เขียน NodeJS ด้วย Javascript ES6 ครับ
